import { test,expect } from '@playwright/test';
import { readFileSync,mkdirSync } from 'node:fs';
import Database from 'better-sqlite3';
const credentials={email:process.env.QA_EMAIL!,password:process.env.QA_PASSWORD!};
const evidence=process.env.QA_EVIDENCE_DIR||'docs/evidence/REQ-008/';
mkdirSync(evidence,{recursive:true});
test('Geschützte vollständige Interviewreise, Persistenz und responsive Ansichten',async({page,request})=>{
 test.setTimeout(90000);
 const env=readFileSync('.env.qa.local','utf8');if(!env.includes('DATABASE_PATH=.data/qa.sqlite'))throw Error('Nur isolierte QA-Datenbank erlaubt.');
 const db=new Database('.data/qa.sqlite');db.prepare('DELETE FROM projects').run();db.prepare('DELETE FROM rateLimit').run();db.close();
 const issues:string[]=[];page.on('pageerror',e=>issues.push(e.message));
 expect((await request.get('/api/workspace')).status()).toBe(401);
 expect((await request.put('/api/workspace',{data:{project:{}}})).status()).toBe(401);
 expect((await request.post('/api/auth/sign-up/email',{data:{}})).status()).toBe(404);
 await page.setViewportSize({width:1440,height:900});await page.goto('/');await expect(page).toHaveURL(/login/);
 await page.screenshot({path:evidence+'login-desktop.png',fullPage:true});
 await page.getByLabel('E-Mail',{exact:true}).fill('unknown@example.invalid');await page.getByLabel('Passwort',{exact:true}).fill('synthetic-invalid-password');await page.getByRole('button',{name:'Arbeitsplatz öffnen'}).click();await expect(page.getByText('Anmeldung nicht möglich. Zugangsdaten prüfen oder später erneut versuchen.',{exact:true})).toBeVisible();
 await page.screenshot({path:evidence+'login-error-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:evidence+'login-error-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:900});
 await page.getByLabel('E-Mail',{exact:true}).fill(credentials.email);await page.getByLabel('Passwort',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'Arbeitsplatz öffnen'}).click();await expect(page).toHaveURL('http://localhost:3000/');
 await expect(page.getByText('Alles beginnt mit einem Projekt.')).toBeVisible();await page.screenshot({path:evidence+'empty-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:evidence+'empty-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:900});
 await page.getByRole('button',{name:'Erstes Projekt anlegen'}).click();await page.getByLabel('Projektbezeichnung',{exact:true}).fill('Analyse Produkt & Markt');await page.getByLabel('Ziel',{exact:true}).fill('Entscheidungen und Zusammenarbeit nachvollziehbar verstehen.');await page.getByLabel('Scope',{exact:true}).fill('Produkt- und Marktmanagement · synthetisches Beispiel');await page.getByLabel('Startdatum').fill('2026-10-12');await page.getByRole('button',{name:'Projekt starten'}).click();await expect(page.getByText('Klarer Blick. Nächster Schritt.')).toBeVisible();
 await page.screenshot({path:evidence+'overview-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:evidence+'overview-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.setViewportSize({width:1440,height:900});
 await page.getByRole('button',{name:/Interview Marktmanagement vorbereiten/}).click();await expect(page.getByText('Vorbereitungscheckliste')).toBeVisible();await page.screenshot({path:evidence+'task-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:evidence+'task-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:900});
 await page.getByRole('checkbox',{name:'Untersuchungsziele abgrenzen'}).check();await page.getByRole('button',{name:'Änderungen speichern'}).click();await expect(page.getByRole('status')).toHaveText('Änderungen gespeichert.');
 await page.getByRole('button',{name:'Interview vorbereiten',exact:true}).click();await page.getByRole('textbox',{name:'Frage 1',exact:true}).fill('Welche konkreten Entscheidungen prägen Ihre Rolle?');await page.getByRole('checkbox',{name:'Frage 6 auswählen'}).uncheck();await page.getByRole('button',{name:'Frage 2 nach oben'}).click();await page.getByRole('button',{name:'Änderungen speichern'}).click();await expect(page.getByRole('status')).toBeVisible();
 await page.screenshot({path:evidence+'interview-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:evidence+'interview-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.setViewportSize({width:1440,height:900});
 await page.getByRole('button',{name:'Druckansicht',exact:true}).click();await expect(page.getByText('Welche konkreten Entscheidungen prägen Ihre Rolle?')).toBeVisible();await expect(page.locator('.print-question')).toHaveCount(6);await page.emulateMedia({media:'print'});await page.screenshot({path:evidence+'print-desktop.png',fullPage:true});await page.pdf({path:evidence+'leitfaden.pdf',format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});await page.getByRole('button',{name:'Zurück zum Leitfaden'}).click();
 await page.getByLabel('Terminstatus').selectOption('durchgeführt');await expect(page.getByRole('checkbox',{name:'Anonymisierte Notizen extern oder zulässig dokumentiert'})).not.toBeChecked();await page.getByLabel('Titel',{exact:true}).fill('Belegarten für Übergaben prüfen');await page.getByLabel('Termin',{exact:true}).fill('2026-10-22');await page.getByRole('button',{name:'Zur Aufgabenliste hinzufügen'}).click();await page.getByRole('button',{name:'Änderungen speichern'}).click();await expect(page.getByRole('status')).toBeVisible();
 await page.reload();await page.getByRole('button',{name:'Interviews',exact:false}).click();await expect(page.getByLabel('Terminstatus')).toHaveValue('durchgeführt');await expect(page.getByRole('textbox',{name:'Frage 2',exact:true})).toHaveValue('Welche konkreten Entscheidungen prägen Ihre Rolle?');await expect(page.getByRole('checkbox',{name:'Anonymisierte Notizen extern oder zulässig dokumentiert'})).not.toBeChecked();
 const data=await page.request.get('/api/workspace');const {projects}=await data.json();const p=projects[0];expect(p.tasks.some((t:{title:string})=>t.title==='Belegarten für Übergaben prüfen')).toBe(true);
 const stale=structuredClone(p);const good=await page.request.put('/api/workspace',{headers:{Origin:'http://localhost:3000'},data:{project:p}});expect(good.status()).toBe(200);const conflict=await page.request.put('/api/workspace',{headers:{Origin:'http://localhost:3000'},data:{project:stale}});expect(conflict.status()).toBe(409);
 const invalid=await page.request.put('/api/workspace',{headers:{Origin:'http://localhost:3000'},data:{project:{...p,title:''}}});expect(invalid.status()).toBe(400);const csrf=await page.request.put('/api/workspace',{headers:{Origin:'https://invalid.example'},data:{project:p}});expect(csrf.status()).toBe(403);
 const cookies=await page.context().cookies();const session=cookies.find(c=>c.name.includes('session_token'));expect(session?.httpOnly).toBe(true);expect(session?.sameSite).toBe('Lax');expect(session?.expires).toBeLessThan(Date.now()/1000+8*3600+30);
 await page.getByRole('button',{name:'Abmelden',exact:true}).click();await expect(page).toHaveURL(/login/);expect((await page.request.get('/api/workspace')).status()).toBe(401);await page.setViewportSize({width:390,height:844});await page.screenshot({path:evidence+'login-mobile.png',fullPage:true});expect(issues).toEqual([]);
});
test('Sessionablauf, Loginlimit, Adminschutz und expliziter Passwortreset',async({request})=>{
 test.setTimeout(30000);
 const {spawnSync}=await import('node:child_process');const {randomBytes}=await import('node:crypto');const {writeFileSync}=await import('node:fs');
 const env=Object.fromEntries(readFileSync('.env.qa.local','utf8').split('\n').filter(l=>l.includes('=')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)]}));if(env.DATABASE_PATH!=='.data/qa.sqlite')throw Error('Nur QA-Datenbank erlaubt.');
 const db=new Database('.data/qa.sqlite');db.prepare('DELETE FROM rateLimit').run();
 const origin={Origin:'http://localhost:3000'};
 expect((await request.post('/api/auth/sign-in/email',{headers:origin,data:{...credentials,rememberMe:false}})).status()).toBe(200);
 db.prepare('UPDATE session SET expiresAt=?').run(new Date(Date.now()-10000).toISOString());expect((await request.get('/api/workspace')).status()).toBe(401);
 const before=db.prepare('SELECT password FROM account WHERE providerId=?').get('credential');
 const result=spawnSync('node',['--import','tsx','scripts/admin.ts','init'],{env:{...process.env,...env,ADMIN_INITIAL_PASSWORD:credentials.password},encoding:'utf8'});expect(result.status).toBe(1);expect(db.prepare('SELECT password FROM account WHERE providerId=?').get('credential')).toEqual(before);
 const newPassword=randomBytes(24).toString('base64url');const reset=spawnSync('node',['--import','tsx','scripts/admin.ts','reset'],{env:{...process.env,...env,ADMIN_INITIAL_PASSWORD:newPassword},encoding:'utf8'});expect(reset.status).toBe(0);expect(db.prepare('SELECT password FROM account WHERE providerId=?').get('credential')).not.toEqual(before);expect(db.prepare('SELECT count(*) AS n FROM session').get()).toEqual({n:0});
 db.prepare('DELETE FROM rateLimit').run();
 expect((await request.post('/api/auth/sign-in/email',{headers:origin,data:credentials})).status()).toBe(401);
 expect((await request.post('/api/auth/sign-in/email',{headers:origin,data:{email:credentials.email,password:newPassword,rememberMe:false}})).status()).toBe(200);
 credentials.password=newPassword;writeFileSync('.env.qa.local',readFileSync('.env.qa.local','utf8').replace(/^QA_PASSWORD=.*$/m,'QA_PASSWORD='+newPassword),{mode:0o600});
 db.prepare('DELETE FROM rateLimit').run();let status=0;for(let i=0;i<6;i++)status=(await request.post('/api/auth/sign-in/email',{headers:origin,data:{email:'unknown@example.invalid',password:'synthetic-invalid-password'}})).status();expect(status).toBe(429);
 db.prepare('DELETE FROM rateLimit').run();db.close();
});
