'use client';
import { useState } from 'react';
import { ArrowRight,CheckCircle2,CircleAlert,GitBranch,Plus,ShieldCheck } from 'lucide-react';
import type { Project } from '@/lib/schema';
import { sevenSDimensions,starPlusDimensions,type StarPlusKey } from '@/lib/frameworks';

const values=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form));
const dimensions=(form:HTMLFormElement)=>new FormData(form).getAll('dimensions') as StarPlusKey[];
const Field=({name,label,required=false,area=false,placeholder=''}:{name:string;label:string;required?:boolean;area?:boolean;placeholder?:string})=><label>{label}{area?<textarea name={name} required={required} placeholder={placeholder}/>:<input name={name} required={required} placeholder={placeholder}/>}</label>;
function DimensionPicker(){return <fieldset className="dimension-picker"><legend>Analyseperspektiven</legend>{starPlusDimensions.map(d=><label key={d.key}><input type="checkbox" name="dimensions" value={d.key}/><span><b>{d.label}</b><small>{d.kind}</small></span></label>)}</fieldset>}
const labelFor=(key:string)=>starPlusDimensions.find(d=>d.key===key)?.label||key;

export default function AnalysisChain({project,change}:{project:Project;change:(fn:(p:Project)=>Project)=>void}){
 const[step,setStep]=useState('auftrag');const[notice,setNotice]=useState('');
 const questions=project.analysisQuestions||[],hypotheses=project.hypotheses||[],evidence=project.evidenceItems||[],findings=project.findings||[],fields=project.actionFields||[],measures=project.measures||[];
 const counts=Object.fromEntries(starPlusDimensions.map(d=>[d.key,questions.filter(x=>x.dimensions.includes(d.key)).length+hypotheses.filter(x=>x.dimensions.includes(d.key)).length+findings.filter(x=>x.dimensions.includes(d.key)).length]));
 const save=(message:string,fn:(p:Project)=>void)=>{change(p=>{fn(p);return p});setNotice(message+' Mit „Änderungen speichern“ dauerhaft sichern.')};
 const inputClass=(active:string)=>step===active?'active':'';
 return <div className="chain-layout">
  <section className="chain-hero"><div><p className="eyebrow">VON DER FRAGE ZUR WIRKSAMKEIT</p><h2>Ihre Begründungskette.</h2><p>Frameworks prüfen Vollständigkeit. Befunde und Empfehlungen entstehen ausschließlich aus Ihrer Evidenz.</p></div><div className="chain-health"><b>{measures.length}</b><span>nachvollziehbare Maßnahme{measures.length===1?'':'n'}</span></div></section>
  <nav className="chain-steps" aria-label="Analysekette">{[['auftrag','Analysefrage',questions.length],['hypothese','Hypothese',hypotheses.length],['evidenz','Evidenz',evidence.length],['befund','Befund',findings.length],['handlung','Handlungsfeld',fields.length],['massnahme','Maßnahme',measures.length],['trace','Nachweis',measures.length]].map(([key,label,count],i)=><button aria-label={label+String(count)+' erfasst'} key={String(key)} className={inputClass(String(key))} onClick={()=>setStep(String(key))}><i>{i+1}</i><span>{label}<small>{count} erfasst</small></span>{i<6&&<ArrowRight size={14}/>}</button>)}</nav>
  {notice&&<div className="notice success" role="status">{notice}</div>}
  <section className="framework-panel panel"><div className="section-heading"><div><p className="eyebrow">METHODISCHE LINSE · KEINE BEWERTUNG</p><h2>Vollständigkeit aus zwei Blickwinkeln.</h2></div><div className="framework-switch"><button aria-pressed={project.frameworkView==='star-plus'} onClick={()=>save('Primäre Framework-Ansicht gewählt.',p=>{p.frameworkView='star-plus'})}>Star + Ergänzungen</button><button aria-pressed={project.frameworkView==='7s'} onClick={()=>save('Alternative 7-S-Ansicht gewählt.',p=>{p.frameworkView='7s'})}>7-S-Orientierung</button></div></div>
   {project.frameworkView==='star-plus'?<div className="framework-grid">{starPlusDimensions.map(d=><article key={d.key}><span>{counts[d.key]||0} Zuordnungen</span><h3>{d.label}</h3><p>{d.description}</p><small>{d.kind}</small></article>)}</div>:<><div className="framework-grid seven-s">{sevenSDimensions.map(d=><article key={d.key}><span>{d.maps.reduce((n,k)=>n+(counts[k]||0),0)} orientierende Zuordnungen</span><h3>{d.label}</h3><p>{d.maps.map(labelFor).join(' · ')}</p></article>)}</div><p className="muted small">7-S zeigt dieselben Inhalte alternativ. Die Zuordnung ist Orientierung und keine vollständige Gleichsetzung.</p></>}
  </section>
  {step==='auftrag'&&<section className="chain-work"><div className="panel form-panel"><p className="eyebrow">01 · ANALYSEAUFTRAG</p><h2>Eine entscheidbare Frage formulieren.</h2><form onSubmit={e=>{e.preventDefault();const v=values(e.currentTarget);save('Analysefrage angelegt.',p=>p.analysisQuestions.push({id:crypto.randomUUID(),question:String(v.question),improvement:String(v.improvement),scope:String(v.scope||''),interfaces:String(v.interfaces||''),inScope:String(v.inScope||''),outOfScope:String(v.outOfScope||''),influence:String(v.influence),successCriteria:String(v.successCriteria||''),constraints:String(v.constraints||''),dimensions:dimensions(e.currentTarget)}));e.currentTarget.reset()}}><Field name="question" label="Zentrale Analysefrage" required area placeholder="Welche organisatorischen Faktoren verzögern Produktentscheidungen?"/><Field name="improvement" label="Angestrebte Verbesserung" required placeholder="Zum Beispiel: kürzere und klarere Produktentscheidungen"/><div className="form-row"><Field name="scope" label="Betrachteter Bereich" placeholder="Rauchmelder-Produktportfolio"/><Field name="interfaces" label="Relevante Schnittstellen" placeholder="Entwicklung, Qualität, Vertrieb"/></div><div className="form-row"><Field name="inScope" label="Im Scope"/><Field name="outOfScope" label="Außerhalb Scope"/></div><Field name="influence" label="Einflussbereich des Auftraggebers" required area/><Field name="successCriteria" label="Erfolgskriterien" area/><Field name="constraints" label="Bekannte Einschränkungen" area/><DimensionPicker/><button className="primary"><Plus size={16}/>Analysefrage anlegen</button></form></div><ItemList title="Bestehende Analysefragen" empty="Noch keine Analysefrage." items={questions.map(q=>({id:q.id,title:q.question,detail:q.improvement,tags:q.dimensions.map(labelFor)}))}/></section>}
  {step==='hypothese'&&<section className="chain-work"><div className="panel form-panel"><p className="eyebrow">02 · PRÜFBARE ANNAHME</p><h2>Hypothese statt Vorfestlegung.</h2><form onSubmit={e=>{e.preventDefault();const v=values(e.currentTarget);save('Hypothese angelegt.',p=>p.hypotheses.push({id:crypto.randomUUID(),questionId:String(v.questionId),description:String(v.description),dimensions:dimensions(e.currentTarget),plannedTest:String(v.plannedTest),status:'offen',rationale:'',supportingEvidenceIds:[],contradictingEvidenceIds:[]}));e.currentTarget.reset()}}><label>Bezug zur Analysefrage<select name="questionId" required defaultValue=""><option value="" disabled>Analysefrage wählen</option>{questions.map(q=><option key={q.id} value={q.id}>{q.question}</option>)}</select></label><Field name="description" label="Hypothese" required area placeholder="Unklare Entscheidungsrechte verlängern die Klärung zwischen Produktmanagement und Entwicklung."/><Field name="plannedTest" label="Geplante Prüfung" required area placeholder="Zwei kontrastierende Produktentscheidungen rekonstruieren und Rollen gegenprüfen."/><DimensionPicker/><button className="primary" disabled={!questions.length}><Plus size={16}/>Hypothese anlegen</button></form></div><ItemList title="Hypothesen" empty="Zuerst eine Analysefrage anlegen." items={hypotheses.map(h=>({id:h.id,title:h.description,detail:h.plannedTest,tags:[h.status,...h.dimensions.map(labelFor)]}))}/></section>}
  {step==='evidenz'&&<section className="chain-work"><div className="panel form-panel"><p className="eyebrow">03 · BELEGLAGE</p><h2>Evidenz mit Grenzen erfassen.</h2><form onSubmit={e=>{e.preventDefault();const v=values(e.currentTarget);const id=crypto.randomUUID();save('Evidenz erfasst und mit der Hypothese verknüpft.',p=>{p.evidenceItems.push({id,summary:String(v.summary),evidenceType:v.evidenceType as Project['evidenceItems'][number]['evidenceType'],sourceType:v.sourceType as Project['evidenceItems'][number]['sourceType'],reference:String(v.reference),date:String(v.date||''),limitations:String(v.limitations||'')});p.hypotheses=p.hypotheses.map(h=>h.id===v.hypothesisId?{...h,[v.stance==='widersprechend'?'contradictingEvidenceIds':'supportingEvidenceIds']:[...h[v.stance==='widersprechend'?'contradictingEvidenceIds':'supportingEvidenceIds'],id]}:h)});e.currentTarget.reset()}}><label>Hypothese<select name="hypothesisId" required defaultValue=""><option value="" disabled>Hypothese wählen</option>{hypotheses.map(h=><option value={h.id} key={h.id}>{h.description}</option>)}</select></label><div className="form-row"><label>Evidenzart<select name="evidenceType">{['Wahrnehmung/Aussage','Beobachtung','Messwert','Interpretation/Hypothese'].map(x=><option key={x}>{x}</option>)}</select></label><label>Quellenart<select name="sourceType">{['Interview','Beobachtung','Dokumentenhinweis','Kennzahl','Rekonstruierter Fall'].map(x=><option key={x}>{x}</option>)}</select></label></div><Field name="summary" label="Anonymisierte Zusammenfassung" required area/><div className="form-row"><Field name="reference" label="Neutrale Quellenkennung" required placeholder="INT-PM-01"/><label>Datum<input type="date" name="date"/></label></div><label>Bezug zur Hypothese<select name="stance"><option value="unterstützend">Unterstützend</option><option value="widersprechend">Widersprechend</option></select></label><Field name="limitations" label="Einschränkungen / Abhängigkeiten" area/><button className="primary" disabled={!hypotheses.length}><Plus size={16}/>Evidenz erfassen</button></form></div><ItemList title="Evidenzregister" empty="Noch keine Evidenz." items={evidence.map(x=>({id:x.id,title:x.summary,detail:(x.reference+' · '+x.sourceType),tags:[x.evidenceType]}))}/></section>}
  {step==='befund'&&<section className="chain-work"><div className="panel form-panel"><p className="eyebrow">04 · BEFUND & URSACHENHYPOTHESE</p><h2>Beobachtung und Erklärung trennen.</h2><form onSubmit={e=>{e.preventDefault();const v=values(e.currentTarget);save('Befund angelegt.',p=>p.findings.push({id:crypto.randomUUID(),description:String(v.description),evidenceIds:new FormData(e.currentTarget).getAll('evidenceIds') as string[],affected:String(v.affected||''),impact:String(v.impact),possibleCauses:String(v.possibleCauses||''),alternatives:String(v.alternatives||''),confidence:v.confidence as Project['findings'][number]['confidence'],confidenceRationale:String(v.confidenceRationale),openQuestions:String(v.openQuestions||''),dimensions:dimensions(e.currentTarget)}));e.currentTarget.reset()}}><Field name="description" label="Festgestellter Zustand" required area/><fieldset><legend>Zugeordnete Evidenz</legend>{evidence.map(x=><label className="check-row" key={x.id}><input type="checkbox" name="evidenceIds" value={x.id}/><span>{x.reference} · {x.summary}</span></label>)}</fieldset><Field name="affected" label="Betroffene Rollen / Schnittstellen / Prozesse" area/><Field name="impact" label="Auswirkung auf das angestrebte Ergebnis" required area/><Field name="possibleCauses" label="Mögliche Ursache – ausdrücklich Hypothese" area/><Field name="alternatives" label="Alternative Erklärung" area/><label>Belastbarkeit<select name="confidence"><option>vorläufig</option><option>plausibel</option><option>belastbar</option></select></label><Field name="confidenceRationale" label="Begründung der Belastbarkeit" required area/><Field name="openQuestions" label="Offene Validierungsfragen" area/><DimensionPicker/><button className="primary" disabled={!evidence.length}><Plus size={16}/>Befund anlegen</button></form></div><ItemList title="Befunde" empty="Noch kein Befund." items={findings.map(f=>({id:f.id,title:f.description,detail:f.impact,tags:[f.confidence,...f.dimensions.map(labelFor)]}))}/></section>}
  {step==='handlung'&&<section className="chain-work"><div className="panel form-panel"><p className="eyebrow">05 · HANDLUNGSFELD</p><h2>Problem, Ursache und Einfluss zusammenführen.</h2><form onSubmit={e=>{e.preventDefault();const v=values(e.currentTarget);save('Handlungsfeld angelegt.',p=>p.actionFields.push({id:crypto.randomUUID(),title:String(v.title),problem:String(v.problem),cause:String(v.cause||''),findingIds:new FormData(e.currentTarget).getAll('findingIds') as string[],dimensions:dimensions(e.currentTarget),influence:String(v.influence),dependencies:String(v.dependencies||''),improvement:String(v.improvement),impact:v.impact as 'niedrig'|'mittel'|'hoch',feasibility:v.feasibility as 'niedrig'|'mittel'|'hoch',priorityRationale:String(v.priorityRationale)}));e.currentTarget.reset()}}><Field name="title" label="Handlungsfeld" required/><Field name="problem" label="Adressiertes Problem" required area/><Field name="cause" label="Adressierte Ursachenhypothese" area/><fieldset><legend>Zugrunde liegende Befunde</legend>{findings.map(x=><label className="check-row" key={x.id}><input type="checkbox" name="findingIds" value={x.id}/><span>{x.description}</span></label>)}</fieldset><Field name="improvement" label="Angestrebte Verbesserung" required area/><Field name="influence" label="Eigener Einflussbereich" required area/><Field name="dependencies" label="Externe Abhängigkeiten" area/><div className="form-row"><label>Erwartete Wirkung<select name="impact"><option>niedrig</option><option>mittel</option><option>hoch</option></select></label><label>Umsetzbarkeit<select name="feasibility"><option>niedrig</option><option>mittel</option><option>hoch</option></select></label></div><Field name="priorityRationale" label="Begründung der Priorisierung" required area/><DimensionPicker/><button className="primary" disabled={!findings.length}><Plus size={16}/>Handlungsfeld anlegen</button></form></div><ItemList title="Handlungsfelder" empty="Noch kein Handlungsfeld." items={fields.map(f=>({id:f.id,title:f.title,detail:f.improvement,tags:['Wirkung '+f.impact,'Umsetzbarkeit '+f.feasibility]}))}/></section>}
  {step==='massnahme'&&<section className="chain-work"><div className="panel form-panel"><p className="eyebrow">06 · MASSNAHME & WIRKSAMKEIT</p><h2>Konkrete Veränderung prüfbar machen.</h2><form onSubmit={e=>{e.preventDefault();const v=values(e.currentTarget);save('Maßnahme mit Wirksamkeitsprüfung angelegt.',p=>p.measures.push({id:crypto.randomUUID(),actionFieldId:String(v.actionFieldId),title:String(v.title),ownerRole:String(v.ownerRole),timing:String(v.timing),expectedEffect:String(v.expectedEffect),successCriteria:String(v.successCriteria),verification:String(v.verification)}));e.currentTarget.reset()}}><label>Handlungsfeld<select name="actionFieldId" required defaultValue=""><option value="" disabled>Handlungsfeld wählen</option>{fields.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><Field name="title" label="Maßnahme" required/><div className="form-row"><Field name="ownerRole" label="Verantwortliche Rolle" required/><Field name="timing" label="Zeitliche Einordnung" required/></div><Field name="expectedEffect" label="Erwartete Wirkung" required area/><Field name="successCriteria" label="Prüfbares Erfolgskriterium" required area/><Field name="verification" label="Vorschlag zur Wirksamkeitsprüfung" required area/><button className="primary" disabled={!fields.length}><Plus size={16}/>Maßnahme anlegen</button></form></div><ItemList title="Maßnahmen" empty="Noch keine Maßnahme." items={measures.map(m=>({id:m.id,title:m.title,detail:m.verification,tags:[m.ownerRole,m.timing]}))}/></section>}
  {step==='evidenz'&&<EvidenceRelations project={project}/>}
  {step==='trace'&&<Traceability project={project}/>}
  {!!project.sessions.length&&<section className="panel session-links"><div><p className="eyebrow">INTERVIEW → ANALYSEFRAGE</p><h2>Leitfäden fachlich verankern.</h2><p className="muted">Die Fragenkopie bleibt eigenständig; die Sitzung verweist auf die zu prüfende Analysefrage.</p></div>{project.sessions.map(session=><label key={session.id}>{session.title} · {session.target}<select value={session.analysisQuestionId||''} onChange={e=>save('Sitzung der Analysefrage zugeordnet.',p=>{p.sessions=p.sessions.map(s=>s.id===session.id?{...s,analysisQuestionId:e.target.value||undefined}:s)})}><option value="">Noch nicht zugeordnet</option>{questions.map(q=><option value={q.id} key={q.id}>{q.question}</option>)}</select></label>)}</section>}
 </div>
}

function ItemList({title,empty,items}:{title:string;empty:string;items:{id:string;title:string;detail:string;tags:string[]}[]}){return <section className="panel chain-list"><h2>{title}</h2>{items.length?items.map(x=><article id={x.id} key={x.id}><CheckCircle2 size={18}/><div><h3>{x.title}</h3><p>{x.detail}</p><div>{x.tags.map(t=><span className="badge" key={t}>{t}</span>)}</div></div></article>):<div className="chain-empty"><CircleAlert/><p>{empty}</p></div>}</section>}
function EvidenceRelations({project}:{project:Project}){return <section className="panel evidence-relations"><p className="eyebrow">UNTERSTÜTZEND UND WIDERSPRECHEND</p><h2>Beleglage je Hypothese</h2>{project.hypotheses.map(h=><article key={h.id}><h3>{h.description}</h3><div><span className="evidence-positive">Unterstützend</span>{h.supportingEvidenceIds.length?h.supportingEvidenceIds.map(id=><p key={id}>{project.evidenceItems.find(e=>e.id===id)?.reference||'Referenz fehlt'}</p>):<p>Keine Evidenz</p>}</div><div><span className="evidence-negative">Widersprechend</span>{h.contradictingEvidenceIds.length?h.contradictingEvidenceIds.map(id=><p key={id}>{project.evidenceItems.find(e=>e.id===id)?.reference||'Referenz fehlt'}</p>):<p>Keine Evidenz</p>}</div></article>)}</section>}
function Traceability({project}:{project:Project}){const measures=project.measures||[];return <section className="panel trace-panel"><div className="section-heading"><div><p className="eyebrow">07 · TRACEABILITY</p><h2>Von der Maßnahme zurück zum Ursprung.</h2></div><GitBranch/></div>{measures.length?measures.map(m=>{const field=project.actionFields.find(x=>x.id===m.actionFieldId);const linkedFindings=project.findings.filter(x=>field?.findingIds.includes(x.id));const evidence=project.evidenceItems.filter(x=>linkedFindings.some(f=>f.evidenceIds.includes(x.id)));const hypotheses=project.hypotheses.filter(h=>evidence.some(e=>h.supportingEvidenceIds.includes(e.id)||h.contradictingEvidenceIds.includes(e.id)));const questions=project.analysisQuestions.filter(q=>hypotheses.some(h=>h.questionId===q.id));return <article className="trace-chain" key={m.id}><div className="trace-node measure"><small>MASSNAHME</small><b>{m.title}</b><p>{m.verification}</p></div><ArrowRight/><div className="trace-node"><small>HANDLUNGSFELD</small><b>{field?.title||'Referenz fehlt'}</b></div><ArrowRight/><div className="trace-column">{linkedFindings.map(f=><div className="trace-node" key={f.id}><small>BEFUND</small><b>{f.description}</b></div>)}</div><ArrowRight/><div className="trace-column">{evidence.map(e=><div className="trace-node" key={e.id}><small>EVIDENZ · {e.evidenceType}</small><b>{e.reference}</b><p>{e.summary}</p></div>)}</div><ArrowRight/><div className="trace-column">{hypotheses.map(h=><div className="trace-node" key={h.id}><small>HYPOTHESE</small><b>{h.description}</b></div>)}{questions.map(q=><div className="trace-node origin" key={q.id}><small>ANALYSEFRAGE</small><b>{q.question}</b></div>)}</div></article>}):<div className="chain-empty"><ShieldCheck/><p>Die Nachweiskette erscheint, sobald eine Maßnahme verknüpft wurde.</p></div>}<p className="muted small">Die Kette zeigt gespeicherte Verknüpfungen, keinen automatischen Kausalitätsnachweis.</p></section>}
