import { chromium,expect } from '@playwright/test';
const base=process.env.PAGES_TEST_URL||'http://localhost:3020/codex-project-Credo/';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},locale:'de-DE'});const errors=[];const api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname.includes('/api/'))api.push(r.url())});
 await page.goto(base);await expect(page.getByText('Klarer Blick. Nächster Schritt.')).toBeVisible();await expect(page.getByText('Interaktive Vorschau',{exact:true})).toBeVisible();await page.screenshot({path:'docs/evidence/CHG-006/overview-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/evidence/CHG-006/overview-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:/Interview Marktmanagement vorbereiten/}).click();await page.getByRole('checkbox',{name:'Untersuchungsziele abgrenzen'}).check();await page.getByRole('button',{name:'Änderungen speichern'}).click();await expect(page.getByRole('status')).toHaveText('Änderungen gespeichert.');await page.getByRole('button',{name:'Interview vorbereiten',exact:true}).click();
 await page.getByRole('textbox',{name:'Frage 1',exact:true}).fill('Welche Entscheidung blieb im synthetischen Vorhaben offen?');await page.getByRole('checkbox',{name:'Frage 9 auswählen'}).uncheck();await page.getByRole('button',{name:'Änderungen speichern'}).click();await expect(page.getByRole('status')).toBeVisible();await page.screenshot({path:'docs/evidence/CHG-006/interview-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/evidence/CHG-006/interview-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 await page.reload();await page.getByRole('button',{name:/Interviews/}).click();await expect(page.getByRole('textbox',{name:'Frage 1',exact:true})).toHaveValue('Welche Entscheidung blieb im synthetischen Vorhaben offen?');await page.getByRole('button',{name:'Druckansicht',exact:true}).click();await expect(page.locator('.print-question')).toHaveCount(8);await page.emulateMedia({media:'print'});await page.screenshot({path:'docs/evidence/CHG-006/print.png',fullPage:true});await page.emulateMedia({media:'screen'});
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Beispiel zurücksetzen'}).click();await expect(page.getByText('Klarer Blick. Nächster Schritt.')).toBeVisible();await page.getByRole('button',{name:/Interviews/}).click();await expect(page.getByRole('textbox',{name:'Frage 1',exact:true})).toHaveValue('Welche Aufgaben und Entscheidungen prägen Ihre Rolle im Produktvorhaben?');
 await page.getByRole('button',{name:'Neues Projekt'}).click();await page.getByLabel('Projektbezeichnung',{exact:true}).fill('Synthetischer Pages-Probelauf');await page.getByLabel('Ziel',{exact:true}).fill('Oberfläche ausprobieren');await page.getByLabel('Scope',{exact:true}).fill('Synthetisch');await page.getByLabel('Startdatum').fill('2026-10-12');await page.getByRole('button',{name:'Projekt starten'}).click();await expect(page.getByText('Projekt mit Sechs-Wochen-Roadmap angelegt.')).toBeVisible();await page.reload();await expect(page.getByRole('combobox',{name:'Projekt wechseln'})).toHaveCount(1);expect(errors).toEqual([]);expect(api).toEqual([]);
 console.log('PASS: static subpath, overview/mobile, checklist, guide editing, save/reload, print selection, reset, new project; no API requests or browser errors.');
}finally{await browser.close()}
